service: product-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
