service: product-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  httpApi:
    cors: true

functions:
  getProductsList:
    handler: src/lambda/getProductsList.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
  getProductsById:
    handler: src/lambda/getProductsById.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get

plugins:
  - serverless-plugin-typescript
