service: product-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  httpApi:
    cors: true
  environment:
    PRODUCTS_TABLE_NAME: !Ref productsTable
    STOCKS_TABLE_NAME: !Ref stocksTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:ListTables"
            - "dynamodb:Scan"
            - "dynamodb:BatchGetItem"
            - "dynamodb:PutItem"
          Resource: "*"

functions:
  getProductsList:
    handler: src/lambda/getProductsList.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
  getProductsById:
    handler: src/lambda/getProductsById.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get
  createProduct:
    handler: src/lambda/createProduct.createProduct
    events:
      - httpApi:
          path: /products
          method: post

resources:
  Resources:
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    stocksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: stocks
        AttributeDefinitions:
          - AttributeName: product_id
            AttributeType: S
        KeySchema:
          - AttributeName: product_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

plugins:
  - serverless-plugin-typescript
